### ISSUE TITLE
Latest code has not been published

### ISSUE THREAD

**Issue by drewnoakes** [bgrins/InstantSprite#10]
The source of http://instantsprite.com/ is out of date. Any chance of deploying the latest from `master`?

**Comment by bgrins** [comment]
Ugh, having problems with ruby / gems locally.  Going to try and get that resolved

**Comment by bgrins** [comment]
OK, I believe http://instantsprite.com/ should be updated with the latest code - can you confirm?

**Comment by drewnoakes** [comment]
Looks great. Thanks!
