### ISSUE TITLE
Bug: not all images are processed in Firefox 38. Resulting image is clipped.

### ISSUE THREAD

**Issue by thomazz-nl** [bgrins/InstantSprite#13]
The resulting png is full size, but after ~94,5 images the remainder is whitespace. This happens when composing a sprite of 117 jpg's (80px square) with the following settings:
offset: 5px
direction: horizontal
filetype: png

browser: Firefox 38.0.5

Google Chrome seems to handle this without any problem. Perhaps Firefox has some kind of processing limit that needs a workaround?

Result: ![index](https://cloud.githubusercontent.com/assets/10218628/7958293/36bef9d2-09ee-11e5-9cc9-b4b5cb2a1f40.png)

**Comment by bgrins** [comment]
It's possibly a bug in Firefox, although I can't reproduce it with 100+ 80x80 jpeg files.  Did you do anything else in the site UI that might be causing the bug?  For reference, I just dragged around 100 80x80 images onto the page, then changed direction to horizontal, then changed offset to 5px, and this is what I see (no clipping):

![screenshot 2015-06-07 08 39 34](https://cloud.githubusercontent.com/assets/95570/8024674/b3c84794-0cf0-11e5-95fe-de92f6a34e2a.png)

**Comment by thomazz-nl** [comment]
Oops forgot to check this...it seems not be an issue anymore: mark as solved.
